## Welcome to Coding Exercise 10: Pandas Groupby

This time, we're going to dig deeper into what can be done in `pandas`, especially `groupby` function. The difficulty of these questions are high, however, mastering these two techniques gives you a very versatile tool in manipulating dataframe shapes.

In [24]:
import pandas as pd
import numpy as np

### Pandas Question 1



Your function name should be `expander` and your function will receive 2 inputs: the dataframe to be expanded, and the constant `n`, the number of rows to expand.

Case:

You are maintaining a dataframe containing types of phones and their variants. This year, to prepare for newer phones to be released, you want to adjust your table so it has a few blank rows to be filled later.

For each type of phone, add `n` rows and fill those 2 rows with `np.nan` value. 

##### Example 1

Suppose you have this input dataframe:

In [25]:
df = pd.DataFrame({
    'Type':['iPhone', 'iPhone', 'iPhone', 'iPhone', 'Samsung', 'Samsung', 'Samsung', 'Samsung'],
    'Variants':['12 Mini', '12', '12 Pro', '12 Pro Max', 'S21 FE', 'S21', 'S21+', 'S21 Ultra']
})

df

Type    Variants
0   iPhone     12 Mini
1   iPhone          12
2   iPhone      12 Pro
3   iPhone  12 Pro Max
4  Samsung      S21 FE
5  Samsung         S21
6  Samsung        S21+
7  Samsung   S21 Ultra

And suppose the `n` value is 4. Then, for each type of phone inside the `Type` column, you have to add 4 more new rows. Leave the variants as `np.nan`.

So, once you type in `expander(input_dataframe = df, n=4)`, the output will be:

In [26]:
df = pd.DataFrame({
    'Type':['iPhone', 'iPhone', 'iPhone', 'iPhone',
            'iPhone', 'iPhone', 'iPhone', 'iPhone',
            'Samsung', 'Samsung', 'Samsung', 'Samsung',
           'Samsung','Samsung', 'Samsung', 'Samsung'],
    'Variants':['12 Mini', '12', '12 Pro', '12 Pro Max', 
                np.nan, np.nan, np.nan, np.nan,
                'S21 FE', 'S21', 'S21+', 'S21 Ultra',
               np.nan, np.nan, np.nan, np.nan]
})

df

Type    Variants
0    iPhone     12 Mini
1    iPhone          12
2    iPhone      12 Pro
3    iPhone  12 Pro Max
4    iPhone         NaN
5    iPhone         NaN
6    iPhone         NaN
7    iPhone         NaN
8   Samsung      S21 FE
9   Samsung         S21
10  Samsung        S21+
11  Samsung   S21 Ultra
12  Samsung         NaN
13  Samsung         NaN
14  Samsung         NaN
15  Samsung         NaN

##### Example 2

Suppose you have this input dataframe:

In [27]:
df = pd.DataFrame({
    'Type':['Xiaomi', 'Xiaomi', 'Redmi', 'Redmi', 'Poco', 'Poco'],
    'Variants':['11', '11 Pro', 'Note 11', 'Note 11 Pro', 'M3 5G', 'F3']
})

df

Type     Variants
0  Xiaomi           11
1  Xiaomi       11 Pro
2   Redmi      Note 11
3   Redmi  Note 11 Pro
4    Poco        M3 5G
5    Poco           F3

And suppose the `n` value is 2. Then, for each type of phone inside the `Type` column, you have to add 2 more new rows. Leave the variants as `np.nan`. 

So, once you type in `expander(input_dataframe = df, n=2)`, the output will be:

In [28]:
df = pd.DataFrame({
    'Type':['Xiaomi', 'Xiaomi', 'Xiaomi', 'Xiaomi', 'Redmi', 'Redmi', 'Redmi', 'Redmi', 'Poco', 'Poco','Poco', 'Poco'],
    'Variants':['11', '11 Pro', np.nan, np.nan, 'Note 11', 'Note 11 Pro', np.nan, np.nan, 'M3 5G', 'F3', np.nan, np.nan]
})

df

Type     Variants
0   Xiaomi           11
1   Xiaomi       11 Pro
2   Xiaomi          NaN
3   Xiaomi          NaN
4    Redmi      Note 11
5    Redmi  Note 11 Pro
6    Redmi          NaN
7    Redmi          NaN
8     Poco        M3 5G
9     Poco           F3
10    Poco          NaN
11    Poco          NaN

#### Constraint

It is impossible for `n` to exceed the number of original rows per group.

For example, in the second example, since originally we only have 2 rows for each brand, (we only have 2 rows for Xiaomi, 2 rows for Redmi, and 2 rows for Poco), it is impossible for `n` to be 3.

In [29]:
def expander(input_dataframe, n):
    ### Write your solution here ###

  dic = dict(tuple(input_dataframe.groupby(input_dataframe.columns[0])))
  unique = input_dataframe['Type'].unique()
  cols = ['Type', 'Variants']
  df = pd.DataFrame(columns=cols, index=range(n))

  for i in range(len(unique)):
    df = dic[unique[i]].copy()
    df["Variants"] = np.nan
    expanded_result = dic[unique[i]].append(df,ignore_index=False)
    print(expanded_result)

### Answer for Example 1

In [30]:
expander(input_dataframe = pd.DataFrame({
    'Type':['iPhone', 'iPhone', 'iPhone', 'iPhone', 'Samsung', 'Samsung', 'Samsung', 'Samsung'],
    'Variants':['12 Mini', '12', '12 Pro', '12 Pro Max', 'S21 FE', 'S21', 'S21+', 'S21 Ultra']
}),n = 4)

     Type    Variants
0  iPhone     12 Mini
1  iPhone          12
2  iPhone      12 Pro
3  iPhone  12 Pro Max
0  iPhone         NaN
1  iPhone         NaN
2  iPhone         NaN
3  iPhone         NaN
      Type   Variants
4  Samsung     S21 FE
5  Samsung        S21
6  Samsung       S21+
7  Samsung  S21 Ultra
4  Samsung        NaN
5  Samsung        NaN
6  Samsung        NaN
7  Samsung        NaN


### Answer for Example 2

In [31]:
expander(input_dataframe = pd.DataFrame({
    'Type':['Xiaomi', 'Xiaomi', 'Redmi', 'Redmi', 'Poco', 'Poco'],
    'Variants':['11', '11 Pro', 'Note 11', 'Note 11 Pro', 'M3 5G', 'F3']
}), n = 2)

     Type Variants
0  Xiaomi       11
1  Xiaomi   11 Pro
0  Xiaomi      NaN
1  Xiaomi      NaN
    Type     Variants
2  Redmi      Note 11
3  Redmi  Note 11 Pro
2  Redmi          NaN
3  Redmi          NaN
   Type Variants
4  Poco    M3 5G
5  Poco       F3
4  Poco      NaN
5  Poco      NaN


### Pandas Question 2

Your function is called `scoring`. The input to your function is one dataframe. 

Case:

You are a teacher maintaining a table of your students' scores on multiple subjects. You want to aggregate per each subject, and see the `minimum, average, and maximum` score of that subject.

##### Example 1:

For example, you have this dataframe.

In [32]:
df = pd.DataFrame({
    'Subject':['Math', 'Math', 'Math', 'Biology', 'Biology', 'Biology', 'Biology'],
    'Student':['Annie', 'Bertholdt', 'Connie', 'Eren', 'Erwin', 'Hange', 'Levi'],
    'Score':[80,70,50,85,90,100,90]
})

df

Subject    Student  Score
0     Math      Annie     80
1     Math  Bertholdt     70
2     Math     Connie     50
3  Biology       Eren     85
4  Biology      Erwin     90
5  Biology      Hange    100
6  Biology       Levi     90

Then, when you run `scoring(df)`, the output will be:

In [33]:
df = pd.DataFrame({
    'Subject':['Math', 'Biology'],
    'Min_Score':[50,85],
    'Average_Score':[66.67, 91.25],
    'Max_Score':[80,100]
})

df

Subject  Min_Score  Average_Score  Max_Score
0     Math         50          66.67         80
1  Biology         85          91.25        100

Explanation: 

For the subject 'Math', the minimum score is 50, the average score is 66.67 (average between 80,70, and 50), the maximum score is 80.

For the subject 'Biology', the minimum score is 85, the average score is 91.25, and the maximum score is 100.

##### Example 2:

For example, you have this dataframe.

In [34]:
df = pd.DataFrame({
    'Subject':['History', 'History', 'History', 'History', 'Sports', 'Sports', 'Sports', 'Sports', 'Sports'],
    'Student':['Zeke', 'Reiner', 'Pieck', 'Porco', 'Armin', 'Floch', 'Sasha', 'Mikasa', 'Falco'],
    'Score':[100,80,90,75,50,80,70,100,60]
})

df

Subject Student  Score
0  History    Zeke    100
1  History  Reiner     80
2  History   Pieck     90
3  History   Porco     75
4   Sports   Armin     50
5   Sports   Floch     80
6   Sports   Sasha     70
7   Sports  Mikasa    100
8   Sports   Falco     60

Then, when you run `scoring(df)`, the output will be:

In [35]:
df = pd.DataFrame({
    'Subject':['History', 'Sports'],
    'Min_Score':[75,50],
    'Average_Score':[86.25,72],
    'Max_Score':[100,100]
})

df

Subject  Min_Score  Average_Score  Max_Score
0  History         75          86.25        100
1   Sports         50          72.00        100

In [36]:
def scoring(df):
    ### Write your solution here ###
    
    recap = df.groupby('Subject').agg(Min_Score=('Score', 'min'),
                              Average=('Score', 'mean'),
                              Max_Price=('Score', 'max'))
    print(recap)

### Answer for Example 1

In [37]:
scoring(df=pd.DataFrame({
    'Subject':['Math', 'Math', 'Math', 'Biology', 'Biology', 'Biology', 'Biology'],
    'Student':['Annie', 'Bertholdt', 'Connie', 'Eren', 'Erwin', 'Hange', 'Levi'],
    'Score':[80,70,50,85,90,100,90]
}))

         Min_Score    Average  Max_Price
Subject                                 
Biology         85  91.250000        100
Math            50  66.666667         80


### Answer for Example 2

In [38]:
scoring(df=pd.DataFrame({
    'Subject':['History', 'History', 'History', 'History', 'Sports', 'Sports', 'Sports', 'Sports', 'Sports'],
    'Student':['Zeke', 'Reiner', 'Pieck', 'Porco', 'Armin', 'Floch', 'Sasha', 'Mikasa', 'Falco'],
    'Score':[100,80,90,75,50,80,70,100,60]
}))

         Min_Score  Average  Max_Price
Subject                               
History         75    86.25        100
Sports          50    72.00        100
